### ISSUE TITLE
Fails on init with IDEA 2023.2

### ISSUE THREAD

**Issue by showbags** [satamas/fortran-plugin#100]
java.lang.Throwable: All stub element types should be created before index initialization is complete.
Please add the class org.jetbrains.fortran.lang.stubs.FortranProgramUnitStub$Type with external ID fortran.BLOCK DATA containing stub element type constants to "stubElementTypeHolder" extension.
Registered extensions: [com.intellij.util.xml.stubs.DomElementTypeHolder, org.intellij.plugins.markdown.lang.MarkdownStubElementTypes, com.intellij.lang.properties.parsing.PropertiesElementTypes, org.jetbrains.fortran.lang.FortranTypes, com.intellij.psi.impl.java.stubs.JavaStubElementTypes, org.jetbrains.plugins.groovy.lang.parser.GroovyStubElementTypes, org.jetbrains.plugins.groovy.lang.parser.GroovyEmptyStubElementTypes, org.jetbrains.kotlin.psi.stubs.elements.KtStubElementTypes, nl.hannahsten.texifyidea.psi.LatexStubElementTypes, nl.hannahsten.texifyidea.psi.BibtexStubElementTypes, com.jetbrains.python.PyStubElementTypes, org.asciidoc.intellij.parser.AsciiDocElementTypes]
Registered lazy ids: [fortran.END_ASSOCIATE_STMT, fortran.STRINGEND, fortran.GE, fortran.SECTION_SUBSCRIPT, fortran.PRINT_STMT, fortran.GENERIC_SPEC, kotlin.CHARACTER_CONSTANT, java.ANNOTATION_METHOD, fortran.COMPONENT_PART, fortran.MULT_EXPR, texify.latex.ENVIRONMENT, fortran.PROTECTED_STMT, kotlin.CLASS_LITERAL_EXPRESSION, fortran.PROCEDURE_DESIGNATOR, fortran.ASSOCIATION, kotlin.NULL, fortran.SUFFIX, texify.latex.Companion, fortran.EQUIVALENCE_OBJECT, java.MODULE, gr.CLASS_TYPE_DEFINITION, fortran.LBRACKET, py.IMPORT_STATEMENT, fortran.BLOCK, fortran.TYPE_GUARD_STMT, java.THROWS_LIST, gr.TYPE_PARAMETER, fortran.END_WHERE_STMT, fortran.ACCESS_STMT, xml.ElementStubSerializer, fortran.UNIT, fortran.CASE_CONSTRUCT, gr.ENUM_TYPE_DEFINITION, fortran.EXIT_STMT, fortran.SUBMODULE_STMT, fortran.ENDFILE_STMT, fortran.WHERE_STMT, fortran.ID_LOOP_STMT, fortran.FORALL_CONSTRUCT, kotlin.REFERENCE_EXPRESSION, fortran.GT, fortran.ENTITY_DECL, fortran.LOCK_STAT, fortran.MASKED_ELSEWHERE_STMT, xml.FileStubSerializer, kotlin.OBJECT_DECLARATION, java.PROVIDES_WITH_LIST, fortran.ELSE_STMT, kotlin.CONTEXT_RECEIVER_LIST, fortran.TRUE, fortran.END_TYPE_STMT, fortran.IFNDEF_MACRO, fortran.ACCEPT_STMT, fortran.ELSE_DIRECTIVE, fortran.COMPONENT_SPEC, fortran.COMPONENT_ATTR_SPEC, py.STAR_IMPORT_ELEMENT, kotlin.LITERAL_STRING_TEMPLATE_ENTRY, fortran.PLUS, gr.PARAMETER, fortran.CONTROL_EDIT, fortran.GOTO_STMT, fortran.LANGUAGE_BINDING_SPEC, fortran.AC_IMPLIED_DO, fortran.DEF_BINARY_OPERATOR_EXPR, java.PERMITS_LIST, fortran.END_MODULE_STMT, fortran.MAIN_PROGRAM, fortran.CASE_VALUE_RANGE, fortran.FUNCTION_SUBPROGRAM, kotlin.BLOCK_CODE_FRAGMENT, kotlin.FILE, fortran.ASSIGNED_GOTO_STMT, fortran.DIRECTIVE_CONTENT, fortran.CONSTRUCT_NAME_DECL, fortran.SAVED_ENTITY, fortran.CONCAT_EXPR, fortran.PARAMETERS_SPEC, py.CLASS_DECLARATION, fortran.NOT, fortran.ADD_EXPR, fortran.CHAR_LENGTH, fortran.ALLOCATE_SHAPE_SPEC, fortran.CASE_SELECTOR, kotlin.ESCAPE_STRING_TEMPLATE_ENTRY, fortran.BIND_ENTITY, fortran.COMPLEX_LITERAL, GroovyCLASS_BODY, fortran.CHAR_SELECTOR, fortran.EXECUTABLE_CONSTRUCT, fortran.MINUS, fortran.CONCURRENT_LOOP_STMT, kotlin.MODIFIER_LIST, fortran.DEFINE_MACRO, fortran.STOP_STMT, kotlin.CONSTRUCTOR_CALLEE, fortran.ASSUMED_SIZE_SPEC, fortran.FORALL_CONSTRUCT_STMT, fortran.IFDEF_MACRO, fortran.SPECIFICATION_STMT, fortran.ALT_RETURN_SPEC, fortran.TARGET_DECL, java.ANNOTATION_PARAMETER_LIST, fortran.UNDERSCORE, fortran.END_SELECT_STMT, kotlin.TYPE_CODE_FRAGMENT, fortran.CALL_STMT, fortran.SUBROUTINE_STMT, fortran.ARRAY_CONSTRUCTOR, fortran.ASYNCHRONOUS_STMT, kotlin.TYPEALIAS, fortran.BOUNDS_REMAPPING, fortran.ELIF_MACRO, kotlin.FUNCTION_TYPE_RECEIVER, fortran.ALLOCATE_COSHAPE_SPEC, fortran.NULLIFY_STMT, fortran.DATA_STMT_CONSTANT, fortran.INTERFACE_STMT, java.USES_STATEMENT, fortran.TYPE_PARAM_DEF_STMT, fortran.DO_TERM_ACTION_STMT, fortran.OPEN_STMT, fortran.RENAME_STMT, fortran.ENDIF_MACRO, kotlin.FUNCTION, fortran.IF_NOT_DEFINED_DIRECTIVE, fortran.DECODE_STMT, fortran.SUBSTRING_RANGE, fortran.CRITICAL_STMT, fortran.LENGTH_SELECTOR, kotlin.VALUE_PARAMETER, fortran.ASSOCIATE_STMT, fortran.EQ, fortran.UNLOCK_STMT, fortran.DEFINED_IO_GENERIC_SPEC, fortran.SIGNED_INT_LITERAL, fortran.AND_EXPR, fortran.ELSEWHERE_STMT, fortran.ATTR_SPEC, fortran.IDENTIFIER, fortran.DECLARATION_CONSTRUCT, fortran.END_ENUM_STMT, kotlin.CONTRACT_EFFECT, fortran.ONLY_STMT, py.SLASH_PARAMETER, fortran.DECLARATION_STMT, fortran.OPTIONAL_STMT, fortran.PROC_POINTER_OBJECT, fortran.COLON, kotlin.CONTRACT_EFFECT_LIST, fortran.POWER_EXPR, fortran.BLOCK_DATA_STMT, fortran.CONTAINS_STMT, fortran.STMT_FUNCTION_STMT, fortran.FINAL_PROCEDURE_STMT, gr.VARIABLE, kotlin.IMPORT_ALIAS, java.TYPE_PARAMETER, fortran.DATA_STMT, java.METHOD, gr.ANNOTATION, fortran.DEFERRED_SHAPE_SPEC, java.CLASS, kotlin.FUNCTION_TYPE, fortran.BOZ_LITERAL, fortran.DATA_STMT_OBJECT, fortran.CLOSE_STMT, fortran.PROC_TARGET, fortran.DOLLAR, kotlin.TYPE_PROJECTION, fortran.ELIF_DIRECTIVE, fortran.AC_VALUE, fortran.FORMAT_STMT, kotlin.SCRIPT, texify.latex.MAGIC_COMMENT, gr.ANNOTATION_TYPE_DEFINITION, fortran.END_PROGRAM_STMT, kotlin.FILE_ANNOTATION_LIST, fortran.USE_STMT, kotlin.VALUE_ARGUMENT, fortran.IMAGE_SET, fortran.END_BLOCK_DATA_STMT, fortran.TYPE_PARAM_ATTR_SPEC, java.NAME_VALUE_PAIR, GroovyENUM_CONSTANTS, fortran.MACRO, fortran.FUNCTION_REFERENCE, py.IMPORT_ELEMENT, fortran.END_FUNCTION_STMT, fortran.BACKSPACE_STMT, java.ENUM_CONSTANT_INITIALIZER, fortran.UNIT_DECL, fortran.LPAR, fortran.NOT_EXPR, fortran.SELECT_TYPE_STMT, fortran.READ_STMT, fortran.TYPE_DECLARATION_STMT, kotlin.PACKAGE_DIRECTIVE, fortran.BINDING_ATTR, fortran.WHERE_CONSTRUCT_STMT, fortran.ALLOCATABLE_DECL, kotlin.PROPERTY, java.PARAMETER, gr.CONSTRUCTOR, fortran.ENDIF_DIRECTIVE, fortran.PROC_DECL, gr.ENUM_CONSTANT_INITIALIZER, kotlin.DYNAMIC_TYPE, kotlin.ANNOTATION_ENTRY, kotlin.INTEGER_CONSTANT, fortran.PROC_POINTER_INIT, fortran.DOUBLEPRECISIONLITERAL, fortran.LETTER_SPEC, kotlin.CLASS_BODY, fortran.LABEL_DO_STMT, fortran.IO_IMPLIED_DO, kotlin.FLOAT_CONSTANT, fortran.ELSE_IF_STMT, fortran.DEFINE_DIRECTIVE, fortran.TARGET_STMT, fortran.END_INTERFACE_STMT, fortran.AND, fortran.ACCESS_ID, fortran.PRIVATE_STMT, fortran.CRITICAL_CONSTRUCT, fortran.TYPE_DECL, py.DECORATOR_CALL, kotlin.TYPE_PARAMETER, kotlin.TYPE_REFERENCE, fortran.FORALL_TRIPLET_SPEC, kotlin.STRING_TEMPLATE, fortran.NEQ, kotlin.PRIMARY_CONSTRUCTOR, kotlin.CONTEXT_RECEIVER, gr.PACKAGE_DEFINITION, fortran.ENUM_DEF, py.ANNOTATION, kotlin.ANNOTATION_TARGET, fortran.INQUIRE_STMT, gr.ENUM_CONSTANT, fortran.NAMED_CONSTANT_DEF, fortran.PROC_COMPONENT_DEF_STMT, fortran.END_IF_STMT, fortran.PROC_INTERFACE, fortran.REWIND_STMT, kotlin.ENUM_ENTRY, fortran.PROCEDURE_DECLARATION_STMT, fortran.ASSIGNMENT_STMT, fortran.PARENTHESISED_EXPR, fortran.EQUIV_EXPR, gr.METHOD, gr.TYPE_PARAMETER_BOUNDS_LIST, fortran.PREFIX_SPEC, fortran.WRITE_STMT, fortran.TYPE_BOUND_PROC_DECL, fortran.DERIVED_TYPE_SPEC, fortran.ENTRY_STMT, fortran.POINTER_ASSMNT, fortran.DATA_STMT_VALUE, fortran.SUBROUTINE_SUBPROGRAM, java.EXTENDS_LIST, fortran.DATA_PATH, kotlin.SUPER_TYPE_LIST, kotlin.SHORT_STRING_TEMPLATE_ENTRY, fortran.DERIVED_TYPE_STMT, xml.AttributeStub, fortran.ENUM_DEF_STMT, java.IMPORT_STATEMENT, java.FIELD, kotlin.BOOLEAN_CONSTANT, fortran.PARAMETER_STMT, fortran.ERROR_STOP_STMT, fortran.IMPLICIT_SPEC, fortran.IF_MACRO, fortran.EQUIVALENCE_SET, fortran.DEFOPERATOR, kotlin.INITIALIZER_LIST, kotlin.NULLABLE_TYPE, py.TUPLE_PARAMETER, fortran.IMPLICIT_STMT, fortran.END_SUBROUTINE_STMT, fortran.FLUSH_STMT, fortran.PROC_ATTR_SPEC, fortran.CODIMENSION_DECL, fortran.PROGRAM_STMT, fortran.NAMELIST_STMT, fortran.DEF_UNARY_OPERATOR_EXPR, fortran.LABEL, fortran.DOT, gr.ANNOTATION_METHOD, fortran.REL_EXPR, java.MODIFIER_LIST, fortran.END_DO_STMT, fortran.INPUT_ITEM, fortran.CONSTANT, kotlin.CLASS_INITIALIZER, fortran.FLOATINGPOINTLITERAL, fortran.AC_SPEC, fortran.SUBSCRIPT_TRIPLET, py.TARGET_EXPRESSION, gr.ANONYMOUS_TYPE_DEFINITION, fortran.SELECT_CASE_STMT, java.EXTENDS_BOUND_LIST, fortran.END_CRITICAL_STMT, kotlin.SUPER_TYPE_CALL_ENTRY, gr.IMPORT, texify.bibtex.ENTRY, fortran.RBRACKET, fortran.CYCLE_STMT, gr.MODIFIER_LIST, fortran.ASSOCIATE_CONSTRUCT, fortran.INTERFACE_SPECIFICATION, fortran.UNKNOWN_MACRO, fortran.VOLATILE_STMT, fortran.UNARY_ADD_EXPR, fortran.BIND_STMT, java.RECORD_HEADER, fortran.IF_STMT, gr.EXTENDS_CLAUSE, fortran.DATA_I_DO_OBJECT, fortran.IMAGE_SELECTOR, fortran.SAVE_STMT, kotlin.LONG_STRING_TEMPLATE_ENTRY, fortran.WHERE_CONSTRUCT, fortran.BLOCK_STMT, fortran.PROCEDURE_STMT, fortran.DATA_STMT_REPEAT, GroovyANNOTATION_ARGUMENT_LIST, fortran.WAIT_STMT, fortran.ENCODE_STMT, fortran.WHILE_LOOP_STMT, fortran.ENUMERATOR_DEF_STMT, GroovyENUM_BODY, fortran.INTENT_STMT, fortran.ARRAYLBR, gr.ANNOTATION_MEMBER_VALUE_PAIR, java.JAVA_FILE, fortran.FORALL_HEADER, fortran.STRINGSTART, fortran.ALLOCATABLE_STMT, fortran.INTERFACE_BLOCK, fortran.INTEGERLITERAL, fortran.COMMON_BLOCK_DECL, fortran.END_BLOCK_STMT, fortran.ENUMERATOR, fortran.LOOP_CONTROL, java.EXPORTS_STATEMENT, py.FUNCTION_DECLARATION, fortran.LOGICAL_NEQ, java.IMPORT_STATIC_STATEMENT, java.TYPE_PARAMETER_LIST, gr.FIELD, fortran.EXPLICIT_COSHAPE_SPEC, fortran.PAUSE_STMT, fortran.LOGICAL_LITERAL, kotlin.COLLECTION_LITERAL_EXPRESSION, fortran.UNDEFINE_MACRO, fortran.ACTUAL_ARG, kotlin.IMPORT_LIST, fortran.CODIMENSION_STMT, java.METHOD_REF_EXPRESSION, fortran.SELECT_TYPE_CONSTRUCT, fortran.TYPE_BOUND_PROCEDURE_STMT, fortran.PARENT_STRING, py.NAMED_PARAMETER, fortran.TYPE_STMT, fortran.IF_DIRECTIVE, gr.IMPLEMENTS_CLAUSE, fortran.RETURN_STMT, gr.INTERFACE_TYPE_DEFINITION, fortran.DATA_STMT_SET, fortran.LABELED_DO_CONSTRUCT, fortran.RPAR, fortran.NUMBER_TYPE_SPEC, gr.THROWS_CLAUSE, java.IMPLEMENTS_LIST, fortran.MODULE, fortran.PERC, fortran.TRUEKWD, GroovyPARAMETER_LIST, fortran.BINARYLITERAL, fortran.SYNC_ALL_STMT, fortran.NONLABEL_DO_STMT, fortran.TYPE_BOUND_PROCEDURE_PART, fortran.POINTER_STMT, xml.XIncludeStub, fortran.DATAEDIT, fortran.IF_THEN_STMT, fortran.STRUCTURE_CONSTRUCTOR, fortran.EOL, kotlin.IMPORT_DIRECTIVE, fortran.END_FORALL_STMT, fortran.ACTUAL_ARG_SPEC, fortran.VALUE_STMT, kotlin.VALUE_ARGUMENT_LIST, fortran.STRINGMIDDLE, fortran.CHARACTER_TYPE_SPEC, fortran.LOCK_STMT, fortran.DATA_POINTER_OBJECT, fortran.UNDEFINE_DIRECTIVE, kotlin.CONSTANT_EXPRESSIONS_TYPES, fortran.NONSTANDARD_KIND_SELECTOR, fortran.OUTPUT_ITEM, fortran.POINTER_ASSIGNMENT_STMT, fortran.EQUIVALENCE_STMT, fortran.FUNCTION_STMT, gr.TRAIT_TYPE_DEFINITION, java.IMPORT_LIST, fortran.TYPE_BOUND_GENERIC_STMT, fortran.COMMA, fortran.CONTINUE_STMT, fortran.ACTION_STMT, fortran.ASSIGN_STMT, fortran.IF_CONSTRUCT, kotlin.SUPER_TYPE_ENTRY, fortran.MODULE_STMT, fortran.DIVDIV, fortran.BLOCK_CONSTRUCT, py.EXCEPT_PART, kotlin.CLASS, java.OPENS_STATEMENT, py.SINGLE_STAR_PARAMETER, fortran.OR, fortran.DATA_IMPLIED_DO, kotlin.PROPERTY_ACCESSOR, fortran.SYNC_MEMORY_STMT, java.PROVIDES_STATEMENT, fortran.DATA_COMPONENT_DEF_STMT, fortran.TYPE_ATTR_SPEC, fortran.COMMON_STMT, fortran.TYPE_PARAM_DECL, py.PARAMETER_LIST, fortran.EQEQ, fortran.OR_EXPR, fortran.ARRAYRBR, GroovyTYPE_PARAMETER_LIST, fortran.CONSTRUCT_NAME, fortran.EXPLICIT_SHAPE_SPEC, kotlin.TYPE_ARGUMENT_LIST, kotlin.TYPE_PARAMETER_LIST, fortran.DERIVED_TYPE_DEF, fortran.SEPARATE_MODULE_SUBPROGRAM, fortran.DIMENSION_STMT, fortran.COLONCOLON, fortran.END_MP_SUBPROGRAM_STMT, kotlin.VALUE_ARGUMENT_NAME, fortran.COMPUTED_GOTO_STMT, java.REQUIRES_STATEMENT, fortran.COMPONENT_DEF_STMT, fortran.IMPLIED_SHAPE_SPEC, fortran.COMPONENT_DECL, fortran.KIND_SELECTOR, fortran.ELSE_MACRO, java.LAMBDA_EXPRESSION, fortran.POINTER_OBJECT, kotlin.DOT_QUALIFIED_EXPRESSION, fortran.PARENT_IDENTIFIER, java.ANONYMOUS_CLASS, java.RECORD_COMPONENT, kotlin.VALUE_PARAMETER_LIST, fortran.DIV, fortran.ALLOCATE_COARRAY_SPEC, fortran.CASE_STMT, fortran.IF_DEFINED_DIRECTIVE, fortran.LOGICAL_EQ, fortran.ALLOCATION, fortran.STRINGLITERAL, fortran.BOUNDS_SPEC, fortran.TYPE_NAME, fortran.CONTIGUOUS_STMT, kotlin.BACKING_FIELD, fortran.FORALL_STMT, fortran.PROC_COMPONENT_ATTR_SPEC, kotlin.ENUM_ENTRY_SUPERCLASS_REFERENCE_EXPRESSION, fortran.INCLUDE_STMT, kotlin.EXPRESSION_CODE_FRAGMENT, fortran.FALSE, fortran.MUL, fortran.MODULE_SUBPROGRAM_PART, kotlin.LAMBDA_ARGUMENT, fortran.NONLABEL_DO_CONSTRUCT, java.ANNOTATION, fortran.POINTER_DECL, fortran.COMPONENT_DATA_SOURCE, kotlin.DELEGATED_SUPER_TYPE_ENTRY, fortran.PREFIX, kotlin.ANNOTATION, fortran.COMMON_BLOCK_OBJECT, java.LITERAL_EXPRESSION, texify.bibtex.Companion, py.FROM_IMPORT_STATEMENT, fortran.BLOCK_DATA, fortran.SYNC_IMAGES_STMT, kotlin.TYPE_CONSTRAINT_LIST, fortran.EXPR, fortran.LE, fortran.SIGNED_REAL_LITERAL, fortran.EXTERNAL_STMT, fortran.REL_OP, gr.RECORD_TYPE_DEFINITION, fortran.INTRINSIC_STMT, texify.latex.COMMANDS, fortran.INTERNAL_SUBPROGRAM_PART, fortran.PROGRAM_UNIT, fortran.LABEL_DECL, fortran.UNKNOWN_DIRECTIVE, fortran.DEALLOCATE_STMT, java.PARAMETER_LIST, fortran.FALSEKWD, fortran.HEXLITERAL, kotlin.TYPE_CONSTRAINT, fortran.MP_SUBPROGRAM_STMT, fortran.ARITHMETIC_IF_STMT, kotlin.USER_TYPE, fortran.SUBSTRING, kotlin.SECONDARY_CONSTRUCTOR, fortran.MULTILINE_STRING_LITERAL, java.CLASS_INITIALIZER, fortran.IMPORT_STMT, fortran.IO_IMPLIED_DO_OBJECT, fortran.LT, fortran.OCTALLITERAL, py.DECORATOR_LIST, gr.PERMITS_CLAUSE, kotlin.INTERSECTION_TYPE, gr.VARIABLE_DECLARATION, fortran.DESIGNATOR, fortran.ALLOCATE_STMT, fortran.QUEST, fortran.END_SUBMODULE_STMT, fortran.BYTE_TYPE_SPEC, fortran.AMPERSAND, fortran.POWER, fortran.ASSUMED_SHAPE_SPEC, fortran.SUBMODULE, fortran.TYPE_PARAM_SPEC, java.ENUM_CONSTANT]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.psi.stubs.IStubElementType.checkNotInstantiatedTooLateWithId(IStubElementType.java:42)
	at com.intellij.psi.stubs.IStubElementType.<init>(IStubElementType.java:26)
	at org.jetbrains.fortran.lang.stubs.FortranStubElementType.<init>(FortranStubElementType.kt:12)
	at org.jetbrains.fortran.lang.stubs.FortranProgramUnitStub$Type.<init>(FortranProgramUnitStub.kt:15)
	at org.jetbrains.fortran.lang.stubs.FortranStubFactoryKt.fortranStubFactory(FortranStubFactory.kt:12)
	at org.jetbrains.fortran.lang.FortranTypes.<clinit>(FortranTypes.java:51)
	at org.jetbrains.fortran.lang.psi.FortranTokenSets.<clinit>(FortranTokenType.kt:72)
	at org.jetbrains.fortran.lang.parser.FortranParserDefinitionBase.getCommentTokens(FortranParserDefinitionBase.kt:17)
	at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding.getTodoIndexer(PlatformIdTableBuilding.java:56)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.acceptFileType(TodoIndex.java:141)
	at com.intellij.util.indexing.hints.BaseFileTypeInputFilter.acceptsFileTypeFastPath(BaseFileTypeInputFilter.kt:37)
	at com.intellij.util.indexing.RequiredIndexesEvaluator.applyFileTypeHints(RequiredIndexesEvaluator.kt:153)
	at com.intellij.util.indexing.RequiredIndexesEvaluator.inputFilerToIndexedFilePredicate(RequiredIndexesEvaluator.kt:93)
	at com.intellij.util.indexing.RequiredIndexesEvaluator.acceptRegularFile(RequiredIndexesEvaluator.kt:123)
	at com.intellij.util.indexing.RequiredIndexesEvaluator.access$acceptRegularFile(RequiredIndexesEvaluator.kt:15)
	at com.intellij.util.indexing.RequiredIndexesEvaluator$indexesForRegularFiles$1.invoke(RequiredIndexesEvaluator.kt:45)
	at com.intellij.util.indexing.RequiredIndexesEvaluator$indexesForRegularFiles$1.invoke(RequiredIndexesEvaluator.kt:45)
	at com.intellij.util.indexing.RequiredIndexesEvaluator.buildHintAwareIndexList(RequiredIndexesEvaluator.kt:54)
	at com.intellij.util.indexing.RequiredIndexesEvaluator.indexesForRegularFiles(RequiredIndexesEvaluator.kt:45)
	at com.intellij.util.indexing.RequiredIndexesEvaluator.getRequiredIndexesForRegularFiles(RequiredIndexesEvaluator.kt:182)
	at com.intellij.util.indexing.RequiredIndexesEvaluator.getRequiredIndexes(RequiredIndexesEvaluator.kt:167)
	at com.intellij.util.indexing.RegisteredIndexes.getRequiredIndexes(RegisteredIndexes.java:192)
	at com.intellij.util.indexing.FileBasedIndexImpl.getRequiredIndexes(FileBasedIndexImpl.java:1526)
	at com.intellij.util.indexing.UnindexedFilesFinder.lambda$getFileStatus$3(UnindexedFilesFinder.java:169)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:676)
	at com.intellij.util.indexing.UnindexedFilesFinder.lambda$getFileStatus$4(UnindexedFilesFinder.java:152)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.util.indexing.UnindexedFilesFinder.getFileStatus(UnindexedFilesFinder.java:109)
	at com.intellij.util.indexing.SingleProviderIterator.processFileRethrowExceptions(SingleProviderIterator.java:113)
	at com.intellij.util.indexing.SingleProviderIterator.processFile(SingleProviderIterator.java:87)
	at com.intellij.openapi.roots.impl.FileIndexBase.lambda$toContentIteratorEx$1(FileIndexBase.java:48)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl$processContentFilesRecursively$visitor$1.visitFileEx(WorkspaceFileIndexImpl.kt:133)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.processContentFilesRecursively(WorkspaceFileIndexImpl.kt:142)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateContentUnderDirectory(FileIndexBase.java:41)
	at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.iterateContentUnderDirectory(ModuleFileIndexImpl.java:29)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateProvidedRootsOfContent(FileIndexBase.java:58)
	at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.iterateContent(ModuleFileIndexImpl.java:66)
	at com.intellij.util.indexing.roots.ModuleIndexableFilesIteratorImpl.iterateFiles(ModuleIndexableFilesIteratorImpl.kt:128)
	at com.intellij.util.indexing.roots.IndexableFilesIterator.iterateFilesInRoots(IndexableFilesIterator.java:94)
	at com.intellij.util.indexing.UnindexedFilesScanner.lambda$collectIndexableFilesConcurrently$7(UnindexedFilesScanner.java:420)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.lambda$invokeConcurrentlyIfPossible$21(PushedFilePropertiesUpdaterImpl.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.roots.impl.FilesScanExecutor.runOnAllThreads$lambda$1(FilesScanExecutor.kt:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by satamas** [comment]
Does it help to invalidate caches and restart?

**Comment by satamas** [comment]
I have updated stub version and released the new plugin version. Hope this helps
