### ISSUE TITLE
Exception in the plugin

### ISSUE THREAD

**Issue by dryabov** [satamas/fortran-plugin#24]
IDE: IntelliJ IDEA Community 2017.3.4 (build IC-173.4548.28)

Error message: `org.jetbrains.fortran.lang.psi.impl.FortranUnitDeclImpl cannot be cast to org.jetbrains.fortran.lang.psi.impl.FortranLabelDeclImpl`

Details:
```
org.jetbrains.fortran.lang.psi.impl.FortranUnitDeclImpl cannot be cast to org.jetbrains.fortran.lang.psi.impl.FortranLabelDeclImpl
java.lang.ClassCastException: org.jetbrains.fortran.lang.psi.impl.FortranUnitDeclImpl cannot be cast to org.jetbrains.fortran.lang.psi.impl.FortranLabelDeclImpl
	at org.jetbrains.fortran.ide.findUsages.FortranLabelDeclFindUsagesHandler$createSearcher$1$buildTaskList$1.invoke(FortranLabelDeclFindUsagesHandler.kt:81)
	at org.jetbrains.fortran.ide.findUsages.FortranLabelDeclFindUsagesHandler$createSearcher$1$buildTaskList$1.invoke(FortranLabelDeclFindUsagesHandler.kt:76)
	at org.jetbrains.fortran.ide.findUsages.FortranLabelDeclFindUsagesHandler$Searcher.executeTasks(FortranLabelDeclFindUsagesHandler.kt:57)
	at org.jetbrains.fortran.ide.findUsages.FortranLabelDeclFindUsagesHandler.searchReferences(FortranLabelDeclFindUsagesHandler.kt:32)
	at org.jetbrains.fortran.ide.findUsages.FortranLabelDeclFindUsagesHandler.findReferencesToHighlight(FortranLabelDeclFindUsagesHandler.kt:39)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(IdentifierHighlighterPass.java:163)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getHighlightUsages(IdentifierHighlighterPass.java:140)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightTargetUsages(IdentifierHighlighterPass.java:196)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:107)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by sgshulman** [comment]
Thank you very much! This error was connected with the file-unit-number navigation. It is not fully implemented in the current version. In the next version, it will work.
