### ISSUE TITLE
Exception preventing CLion opening Fortran file

### ISSUE THREAD

**Issue by kbthomp1** [satamas/fortran-plugin#32]
I'm unable to open an existing Fortran file in CLion.  In trying to debug the issue, I went through the following steps:

1. Created new fortran source file
2. Copied and pasted original source file contents into the newly created file

This led to an `AssertionError` in the Fortran plugin:

```
java.lang.AssertionError: (598,598), text: , language = Language: Fortran
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:111)
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:92)
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:77)
	at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:60)
	at org.jetbrains.fortran.ide.folding.FortranFoldingBuilder$FoldingVisitor.foldBetweenStatements(FortranFoldingBuilder.kt:145)
	at org.jetbrains.fortran.ide.folding.FortranFoldingBuilder$FoldingVisitor.visitDeclarationConstruct(FortranFoldingBuilder.kt:101)
	at org.jetbrains.fortran.lang.psi.FortranVisitor.visitInterfaceBlock(FortranVisitor.java:692)
	at org.jetbrains.fortran.lang.psi.impl.FortranInterfaceBlockImpl.accept(FortranInterfaceBlockImpl.java:27)
	at org.jetbrains.fortran.lang.psi.impl.FortranInterfaceBlockImpl.accept(FortranInterfaceBlockImpl.java:31)
	at org.jetbrains.fortran.ide.folding.FortranFoldingBuilder$buildFoldRegions$1.execute(FortranFoldingBuilder.kt:24)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:882)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.fortran.lang.psi.impl.FortranInterfaceBlockImpl.accept(FortranInterfaceBlockImpl.java:32)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:883)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:878)
	at org.jetbrains.fortran.ide.folding.FortranFoldingBuilder.buildFoldRegions(FortranFoldingBuilder.kt:24)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:71)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:239)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:225)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:97)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:86)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:82)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.a(CodeFoldingManagerImpl.java:298)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:284)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.e(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The issue appears to be related to the `include` statement, and I've attached a minimal working example to replicate the issue.

[source_to_replicate_issue.zip](https://github.com/satamas/fortran-plugin/files/2287246/source_to_replicate_issue.zip)

**Comment by satamas** [comment]
It should be fixed now. Problem was that I was trying to fold code from included file.

**Comment by kbthomp1** [comment]
Thanks! That fixed it.
