### ISSUE TITLE
CLioin Error while debugging with a variable watch

### ISSUE THREAD

**Issue by wardev** [satamas/fortran-plugin#40]
I was debugging a Fortran program and CLion told me an error occurred and I should report it to the developers. Not sure if it is a real error if it is just being noisy.

Steps to reproduce:

1. Debug a Fortran program with GDB, gfortran.
2. Create a watch on a private or protected module variable.
3. Continue stepping until the module goes out of scope.
4. CLion tells me an error occurred.

Again not sure it's a real error because I would not expect to not be able to access the variable from outside the module.

Stacktrace:

```
java.lang.Throwable: Empty PSI elements must not be passed to createDescriptor. Start: NONSTANDARD_KIND_SELECTOR, end: NONSTANDARD_KIND_SELECTOR, startContainingFile: FILE
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java:61)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:83)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:72)
	at com.intellij.codeInspection.ProblemsHolder.registerProblem(ProblemsHolder.java:66)
	at org.jetbrains.fortran.ide.inspections.FortranNonstandardKindInspection$buildVisitor$1.visitNonstandardKindSelector(FortranNonstandardKindInspection.kt:31)
	at org.jetbrains.fortran.lang.psi.impl.FortranNonstandardKindSelectorImpl.accept(FortranNonstandardKindSelectorImpl.java:20)
	at org.jetbrains.fortran.lang.psi.impl.FortranNonstandardKindSelectorImpl.accept(FortranNonstandardKindSelectorImpl.java:24)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:295)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:263)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:260)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:260)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by satamas** [comment]
Thanks for submitting issue. I suppose that it is a real error that is related with inability of fortran parser to parse standalone statement. I'll take look at this and fix asap

**Comment by satamas** [comment]
I can't reproduce issue locally and it doesn't look to be related with debug. 
Exception says that PsiElement of non-standard kind selector (for example, integer * 8) is empty, but this is not possible because such psi element must contain at least asterisk. My only idea is that intellij somehow updates PSI tree without reparsing file which leads to empty PSI element that can't be empty in normal cases.

**Comment by wardev** [comment]
Thanks for taking a look. (And for making this plugin!). Based on your comments I tried a few more things. It is reproduceable for me and it is not related to debugging, as you guessed. I can now trigger this just by opening certain files. Is there a way to figure out which line is causing the issue? Is there a log file that would give more details?

The file that causes the error is a f90 subroutine that doesn't have any of the old style `*kind` type selectors. It does include a file, using the include statement, that has many `integer*4` declarations.

**Comment by satamas** [comment]
> It does include a file, using the include statement, that has many integer*4 declarations.
Thanks for investigating, I think this is it. Each include statement produces virtal PSI elements and virtual PSI elements have zero textRange even if they contain text. Will fix it.
