### ISSUE TITLE
Getting a fatal error in Pycharm 2019.3.2

### ISSUE THREAD

**Issue by andrewcoughtrie** [satamas/fortran-plugin#56]
Any ideas as to whats going on?

`java.lang.ClassCastException: class org.jetbrains.fortran.lang.parser.FortranPreprocessorAwareBuilderAdapter cannot be cast to class com.intellij.lang.impl.PsiBuilderImpl (org.jetbrains.fortran.lang.parser.FortranPreprocessorAwareBuilderAdapter is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @49ef8196; com.intellij.lang.impl.PsiBuilderImpl is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @36d4b5c)
	at com.intellij.lang.parser.GeneratedParserUtilBase.isWhitespaceOrComment(GeneratedParserUtilBase.java:414)
	at com.intellij.lang.parser.GeneratedParserUtilBase.reportFrameError(GeneratedParserUtilBase.java:821)
	at com.intellij.lang.parser.GeneratedParserUtilBase.enter_section_(GeneratedParserUtilBase.java:461)
	at com.intellij.lang.parser.GeneratedParserUtilBase.enter_section_(GeneratedParserUtilBase.java:453)
	at org.jetbrains.fortran.lang.parser.FortranParserUtil.enter_section_(FortranParserUtil.kt:152)
	at org.jetbrains.fortran.lang.parser.FortranParser.expr_0(FortranParser.java:14302)
	at org.jetbrains.fortran.lang.parser.FortranParser.expr(FortranParser.java:14293)
	at org.jetbrains.fortran.lang.parser.FortranParser.subscript_triplet_0_0(FortranParser.java:12279)
	at org.jetbrains.fortran.lang.parser.FortranParser.subscript_triplet_0(FortranParser.java:12270)
	at org.jetbrains.fortran.lang.parser.FortranParser.subscript_triplet(FortranParser.java:12259)
	at org.jetbrains.fortran.lang.parser.FortranParser.section_subscript(FortranParser.java:11535)
	at org.jetbrains.fortran.lang.parser.FortranParser$66.parse(FortranParser.java:14876)
	at org.jetbrains.fortran.lang.parser.FortranParser.list(FortranParser.java:9021)
	at org.jetbrains.fortran.lang.parser.FortranParser.data_reference_element_1_0_1(FortranParser.java:3275)
	at org.jetbrains.fortran.lang.parser.FortranParser.data_reference_element_1_0(FortranParser.java:3266)
	at org.jetbrains.fortran.lang.parser.FortranParser.data_reference_element_1(FortranParser.java:3256)
	at org.jetbrains.fortran.lang.parser.FortranParser.data_reference_element(FortranParser.java:3247)
	at org.jetbrains.fortran.lang.parser.FortranParser.data_path_start(FortranParser.java:3181)
	at org.jetbrains.fortran.lang.parser.FortranParser.data_path(FortranParser.java:3135)
	at org.jetbrains.fortran.lang.parser.FortranParser.designator_0(FortranParser.java:14463)
	at org.jetbrains.fortran.lang.parser.FortranParser.designator(FortranParser.java:14452)
	at org.jetbrains.fortran.lang.parser.FortranParser.assignment_stmt(FortranParser.java:941)
	at org.jetbrains.fortran.lang.parser.FortranParser.action_stmt(FortranParser.java:333)
	at org.jetbrains.fortran.lang.parser.FortranParser.execution_part_construct_1(FortranParser.java:6497)
	at org.jetbrains.fortran.lang.parser.FortranParser.execution_part_construct(FortranParser.java:6463)
	at org.jetbrains.fortran.lang.parser.FortranParser.block_0(FortranParser.java:1400)
	at org.jetbrains.fortran.lang.parser.FortranParser.block(FortranParser.java:1387)
	at org.jetbrains.fortran.lang.parser.FortranParser.nonlabel_do_construct(FortranParser.java:9684)
	at org.jetbrains.fortran.lang.parser.FortranParser.executable_construct(FortranParser.java:6442)
	at org.jetbrains.fortran.lang.parser.FortranParser.execution_part_construct_1(FortranParser.java:6499)
	at org.jetbrains.fortran.lang.parser.FortranParser.execution_part_construct(FortranParser.java:6463)
	at org.jetbrains.fortran.lang.parser.FortranParser.block_0(FortranParser.java:1400)
	at org.jetbrains.fortran.lang.parser.FortranParser.block(FortranParser.java:1387)
	at org.jetbrains.fortran.lang.parser.FortranParser.if_construct(FortranParser.java:7451)
	at org.jetbrains.fortran.lang.parser.FortranParser.executable_construct(FortranParser.java:6444)
	at org.jetbrains.fortran.lang.parser.FortranParser.execution_part_construct_1(FortranParser.java:6499)
	at org.jetbrains.fortran.lang.parser.FortranParser.execution_part_construct(FortranParser.java:6463)
	at org.jetbrains.fortran.lang.parser.FortranParser.block_0(FortranParser.java:1400)
	at org.jetbrains.fortran.lang.parser.FortranParser.block(FortranParser.java:1387)
	at org.jetbrains.fortran.lang.parser.FortranParser.subroutine_subprogram(FortranParser.java:12224)
	at org.jetbrains.fortran.lang.parser.FortranParser.module_subprogram_1(FortranParser.java:9413)
	at org.jetbrains.fortran.lang.parser.FortranParser.module_subprogram(FortranParser.java:9365)
	at org.jetbrains.fortran.lang.parser.FortranParser.module_subprogram_part_2_0(FortranParser.java:9465)
	at org.jetbrains.fortran.lang.parser.FortranParser.module_subprogram_part_2(FortranParser.java:9453)
	at org.jetbrains.fortran.lang.parser.FortranParser.module_subprogram_part(FortranParser.java:9428)
	at org.jetbrains.fortran.lang.parser.FortranParser.module_3(FortranParser.java:9316)
	at org.jetbrains.fortran.lang.parser.FortranParser.module(FortranParser.java:9292)
	at org.jetbrains.fortran.lang.parser.FortranParser.program_unit_1(FortranParser.java:11144)
	at org.jetbrains.fortran.lang.parser.FortranParser.program_unit(FortranParser.java:11124)
	at org.jetbrains.fortran.lang.parser.FortranParser.program_0(FortranParser.java:11056)
	at org.jetbrains.fortran.lang.parser.FortranParser.program(FortranParser.java:11044)
	at org.jetbrains.fortran.lang.parser.FortranParser.file(FortranParser.java:6742)
	at org.jetbrains.fortran.lang.parser.FortranParser.parse_root_(FortranParser.java:35)
	at org.jetbrains.fortran.lang.parser.FortranParser.parse_root_(FortranParser.java:31)
	at org.jetbrains.fortran.lang.parser.FortranParser.parseLight(FortranParser.java:26)
	at org.jetbrains.fortran.lang.parser.FortranParser.parse(FortranParser.java:18)
	at org.jetbrains.fortran.lang.parser.FortranFileParser.parse(FortranFileParser.kt:22)
	at org.jetbrains.fortran.lang.stubs.FortranFileStub$Type.parseContents(FortranFileStub.kt:18)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:189)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:564)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:188)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:243)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:40)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.pushChildren(DefaultStubBuilder.java:112)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:82)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:72)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:50)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:39)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:84)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.lambda$readOrBuild$0(StubTreeLoaderImpl.java:70)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:70)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:608)
	at com.intellij.psi.impl.source.PsiFileImpl.getStub(PsiFileImpl.java:570)
	at org.jetbrains.fortran.lang.psi.FortranFile$programUnits$$inlined$runReadAction$1.compute(actions.kt:79)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:807)
	at org.jetbrains.fortran.lang.psi.FortranFile.getProgramUnits(FortranFile.kt:25)
	at org.jetbrains.fortran.lang.resolve.FortranPathReferenceImpl.programUnitsFromFile(FortranPathReferenceImpl.kt:312)
	at org.jetbrains.fortran.lang.resolve.FortranPathReferenceImpl.resolveInProjectFiles(FortranPathReferenceImpl.kt:218)
	at org.jetbrains.fortran.lang.resolve.FortranPathReferenceImpl.resolveName(FortranPathReferenceImpl.kt:164)
	at org.jetbrains.fortran.lang.resolve.FortranPathReferenceImpl.resolveWithoutFiltering(FortranPathReferenceImpl.kt:59)
	at org.jetbrains.fortran.lang.resolve.FortranPathReferenceImpl.resolveInner(FortranPathReferenceImpl.kt:23)
	at org.jetbrains.fortran.lang.resolve.FortranReferenceBase$multiResolve$1.resolve(FortranReferenceBase.kt:24)
	at org.jetbrains.fortran.lang.resolve.FortranReferenceBase$multiResolve$1.resolve(FortranReferenceBase.kt:13)
	at org.jetbrains.fortran.lang.resolve.FortranReferenceBase$multiResolve$1.resolve(FortranReferenceBase.kt:23)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:147)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:146)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:177)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at org.jetbrains.fortran.lang.resolve.FortranReferenceBase.multiResolve(FortranReferenceBase.kt:23)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:387)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:365)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:237)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:209)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)`

**Comment by satamas** [comment]
It's a bug. Will fix it today

**Comment by satamas** [comment]
Should be fixed now, please check

**Comment by andrewcoughtrie** [comment]
All works fine now, thanks.
