### ISSUE TITLE
Exception in plugin Fortran (2020.3) (CLion 2020.3 on Ubuntu 20.04)

### ISSUE THREAD

**Issue by kostyfisik** [satamas/fortran-plugin#73]
I have no idea how to fix this, so it stops me to check fix for #59 
```
com.intellij.diagnostic.PluginException: org.jetbrains.fortran.ide.newProject.FortranProjectGenerator PluginClassLoader[PluginDescriptor(name=Fortran, id=org.jetbrains.fortran, path=/home/tig/.local/share/JetBrains/CLion2020.3/fortran-plugin, version=2020.3)] com.intellij.ide.plugins.cl.PluginClassLoader@70b06535 [Plugin: org.jetbrains.fortran]
	at com.intellij.serviceContainer.ComponentManagerImplKt.createPluginExceptionIfNeeded(ComponentManagerImpl.kt:1040)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$createPluginExceptionIfNeeded(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:804)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:40)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:69)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:501)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:435)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.calcExtensionList(ExtensionPointImpl.java:246)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:240)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:42)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$Customization.getProjectGenerators(AbstractNewProjectStep.java:119)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.updateActions(AbstractNewProjectStep.java:76)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.<init>(AbstractNewProjectStep.java:59)
	at com.jetbrains.cidr.cpp.cmake.projectWizard.CLionCMakeNewProjectStep.<init>(CLionCMakeNewProjectStep.java:32)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:241)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:221)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:570)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1621)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:15)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.fortran.ide.newProject.FortranProjectGenerator PluginClassLoader[PluginDescriptor(name=Fortran, id=org.jetbrains.fortran, path=/home/tig/.local/share/JetBrains/CLion2020.3/fortran-plugin, version=2020.3)] com.intellij.ide.plugins.cl.PluginClassLoader@70b06535
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:75)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:37)
	... 38 more
```

**Comment by sgshulman** [comment]
@kostyfisik Thank you for reporting this problem.

@satamas clion.jar is lost from the plugin release. The latest release is even smaller than the previous one. Please, restore the lost files.

**Comment by satamas** [comment]
Sorry about that. I've forgot about changes in the plugin build process and published an incomplete version of the plugin. It should be fixed now

**Comment by sgshulman** [comment]
@satamas all previous plugin versions https://plugins.jetbrains.com/plugin/9699-fortran/versions were called fortran-plugin.zip. The new archive is clion.zip. Is am not sure this is correct and good.

**Comment by satamas** [comment]
It's named so because it's the result of building clion module with classes for CLion. I agree that it's a bad naming, will fix it, but it's not a problem

**Comment by kostyfisik** [comment]
Works fine now! Thank you for you support!
